name: Workflow

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: Build and run all tests and checks
    timeout-minutes: 5
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/<your-pypi-project-name>
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.10.8"

      - uses: Gr1N/setup-poetry@v8
        name: Install poetry
        with:
          poetry-version: 1.2.2

      - name: Install python dependencies
        run: poetry install

      - name: Check types
        run: make lint

      - name: Check formatting
        run: make format

      - name: Run test
        run: make test

      - name: Build
        run: make all

